import type { CliPreset } from '../../types/workspace';
export const builtInPresets: CliPreset[] = [
  {
    id: 'codex',
    name: 'Codex CLI',
    command: 'codex',
    args: [],
    category: 'Coding Agents',
    icon: '>_',
    builtIn: true,
  },
  {
    id: 'claude',
    name: 'Claude Code',
    command: 'claude',
    args: [],
    category: 'Coding Agents',
    icon: '>_',
    builtIn: true,
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    command: 'gemini',
    args: [],
    category: 'Coding Agents',
    icon: '>_',
    builtIn: true,
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    command: 'copilot',
    args: [],
    category: 'Coding Agents',
    icon: '>_',
    builtIn: true,
  },
  {
    id: 'cursor-agent',
    name: 'Cursor Agent',
    command: 'cursor-agent',
    args: [],
    category: 'Coding Agents',
    icon: '>_',
    builtIn: true,
  },
  {
    id: 'powershell',
    name: 'PowerShell',
    command: 'powershell.exe',
    args: ['-NoLogo'],
    category: 'Shells',
    icon: 'PS',
    builtIn: true,
  },
  {
    id: 'cmd',
    name: 'Command Prompt',
    command: 'cmd.exe',
    args: [],
    category: 'Shells',
    icon: '>_',
    builtIn: true,
  },
  {
    id: 'wsl',
    name: 'WSL',
    command: 'wsl.exe',
    args: [],
    category: 'Shells',
    icon: '>_',
    builtIn: true,
  },
];
